In [1]:
import ktrain
import tensorflow as tf

In [2]:
new_model = tf.keras.models.load_model('./cnn_model')

In [3]:
import pickle
with open('./cnn_predictor/tf_model.preproc', 'rb') as f: preproc = pickle.load(f)

In [4]:
new_predict = ktrain.get_predictor(new_model, preproc)

In [5]:
new_predict.model.load_weights('./cnn_predictor/tf_model.h5')

In [171]:
new_predict.explain('The defendant admitted his crime, so I add two years.')

In [10]:
embeddings = new_model.weights[0].numpy()

In [8]:
new_model.summary()

Model: "model_2"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_3 (InputLayer)            [(None, 5000)]       0                                            
__________________________________________________________________________________________________
embedding_2 (Embedding)         (None, 5000, 100)    5000000     input_3[0][0]                    
__________________________________________________________________________________________________
conv1d_10 (Conv1D)              (None, 4999, 32)     6432        embedding_2[0][0]                
__________________________________________________________________________________________________
conv1d_11 (Conv1D)              (None, 4998, 32)     9632        embedding_2[0][0]                
____________________________________________________________________________________________

In [11]:
embeddings

array([[ 0.02031903,  0.04933965,  0.02865754, ..., -0.02265048,
         0.02572821, -0.00303656],
       [-0.04776132, -0.02554737, -0.05228696, ...,  0.03096877,
        -0.01573466,  0.03483898],
       [-0.00116059, -0.0070656 ,  0.0184384 , ...,  0.01672707,
         0.01151342, -0.00386575],
       ...,
       [-0.02912697, -0.04488286,  0.02484139, ..., -0.02298559,
         0.04920203,  0.0395076 ],
       [ 0.0131227 , -0.01408738, -0.03493637, ...,  0.03300157,
         0.00480126,  0.03733854],
       [ 0.00314789,  0.01440853, -0.0426978 , ...,  0.00273298,
         0.02354116, -0.02656016]], dtype=float32)

In [256]:
preproc.undo([10914])

'cav0014'

In [125]:
embeddings.shape

(50000, 100)

In [250]:
contrary = embeddings[5139,:]

In [251]:
from sklearn.metrics.pairwise import cosine_similarity

In [252]:
contrary_sim = cosine_similarity(contrary.reshape(1,-1), embeddings)

In [253]:
contrary_sim.argsort().flatten()[-10:]

array([11716, 21951, 10914, 37852, 38221,  1798, 43605, 11158,  6786,
        5139])

In [249]:
preproc.tok.texts_to_sequences(['lose'])

[[5139]]

In [149]:
preproc.preprocess_test('As the perpetrator is the sole breadwinner for his family, I reduce his sentence by two years.')

94 test sequences
test sequence lengths:
	mean : 1
	95percentile : 1
	99percentile : 1
x_test shape: (94,5000)


(array([[  0,   0,   0, ...,   0,   0,   6],
        [  0,   0,   0, ...,   0,   0, 296],
        [  0,   0,   0, ...,   0,   0,   0],
        ...,
        [  0,   0,   0, ...,   0,   0, 249],
        [  0,   0,   0, ...,   0,   0, 296],
        [  0,   0,   0, ...,   0,   0,   0]], dtype=int32),
 None)